name: Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ“‚ Listar arquivos no workspace (debug)
        run: ls -R

      - name: ğŸ“Œ Confirmar diretÃ³rio atual
        run: pwd

      - name: ğŸ“Œ Instalar Python e dependÃªncias
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ğŸ“¦ Instalar dependÃªncias do Robot Framework
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-faker
          pip install selenium

      - name: ğŸ–¥ï¸ Instalar Google Chrome e ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chromedriver --version

      - name: ğŸš€ Executar testes com Robot Framework
        run: |
          cd projeto-automacao/tests && robot --outputdir results features/

      - name: ğŸ“¤ Upload dos resultados
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorios_robot
          path: projeto-automacao/tests/results/
